import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryProvider } from "@/helpers/QueryClientProvider";
import { TaskProvider } from "@/helpers/context";
import "@/styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crud app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <TaskProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </TaskProvider>
    </ReactQueryProvider>
  );
}
